spring:
  application:
    name: citybank
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.164.20.237:1521:orcl
    username: scott
    password: tiger
  redis:
    clusterPassw: citybank
    clusterNodes: 10.164.20.237:6379,10.164.20.237:6380,10.164.20.237:6381
logging:
  level:
    org.springframework: INFO
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/