spring:
  application:
    name: citybank
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.164.20.222:1521:orcl
    username: scott
    password: tiger
logging:
  level:
    org.springframework: INFO
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
common:
  jedis:
    config:
      nodes: 10.164.20.222:6379,10.164.20.222:6380,10.164.20.222:6381
      max-redirects: 3