spring:
  cache:
    type: redis
  application:
    name: citybank
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: scott
    password: tiger
  redis:
    cluster:
      nodes:
      - 10.164.16.136:6379,10.164.16.136:6380,10.164.16.136:6381
  jedis:
    clusterNodes: 10.164.16.136:6379,10.164.16.136:6380,10.164.16.136:6381
  session:
    store-type: redis
logging:
  level:
    org.springframework: INFO
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/