spring:
  cache:
    type: redis
  application:
    name: citybank
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: scott
    password: tiger
  redis:
    password: citybank
    timeout: 60000
    cluster:
      max-redirects: 3
      nodes:
      - 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
  session:
    store-type: redis
  jedis:
    clusterNodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
logging:
  level:
    org.springframework: INFO
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/